### PR TITLE
Update compilerplugin, scalapb-runtime to 0.10.10

### PR DESCRIPTION
**Pull request by dziemba**

### CODE REVIEW

**Comment by oberkowitz** [comment]
@dziemba So I've spent some time looking at it and it seems like there is a new interface `CodeGenApp` that is the recommended way to build a protoc compiler plugin with sbt. I don't understand exactly what the difference is and I haven't attempted to rewrite our code generation in it yet, but it might be a worthy experiment in order to avoid some potential deprecation as things get pulled out of the `protocbridge` package. 

I can take a look more later, but this seems to be a potential avenue to try out

https://scalapb.github.io/docs/writing-plugins

**Comment by dziemba** [comment]
Thanks for finding this out! I can also have a look at this at some point if you're busy, I'd also like to know more about the twinagle internals.

**Comment by oberkowitz** [comment]
@dziemba I just ended up doing it because once I figured out what to do, it was just a 5 minute job. Very light change on top of what you had, just using the new interface which is similar to the previous one just with some wrapper types

**Review by ccmtaylor — APPROVED** [review]
nice, thanks all!

**Comment by dziemba** [comment]
Cool, thanks @oberkowitz !

**Pull request merged**
